import { Inter } from "next/font/google";
import "./globals.css";
import Dashes from "@/components/Shared/Dashes"
import Logo from "@/components/Shared/Logo"
import Navbar from "@/components/Shared/Navbar"
import localFont from "next/font/local"
import ProjectBtn from "@/components/Shared/ProjectBtn"
import Footer from "@/components/Shared/Footer"

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ["latin"] });
const NeueMontreal = localFont({
  src: [
    {
      path: './../font/NeueMontreal-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './../font/NeueMontreal-Bold.otf',
      weight: '700',
      style: 'normal',
    }
  ],
})

export const metadata = {
  title: "Alphamark™ Branding Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={NeueMontreal.className}>
        <Dashes/>
        <Logo/>
        <Navbar/>
        <ProjectBtn/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
